# Generated by Django 4.2.4 on 2023-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
